"""Adds products.price and modifies users columns

Revision ID: 4d209dcd2f23
Revises: df5e911045f3
Create Date: 2024-06-26 22:36:29.158232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d209dcd2f23'
down_revision: Union[str, None] = 'df5e911045f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.DECIMAL(precision=16, scale=4), nullable=False))
    # op.add_column('users', sa.Column('user_name', sa.VARCHAR(length=255), nullable=True))
    op.alter_column('users', 'language_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # op.drop_column('users', 'username')
    # Actually renamed username column
    op.alter_column('users','username',new_column_name='user_name')
    # Change column products.description from unspecified to VARCHAR(3000)
    op.alter_column('products','description',type_=sa.VARCHAR(3000))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('users', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # op.drop_column('users', 'user_name')
    op.drop_column('products', 'price')
    # Renaming of column
    op.alter_column('users','user_name',new_column_name='username')
    # Change column products.description from VARCHAR(3000) to String()
    op.alter_column('products','description',type_=sa.String())
    # ### end Alembic commands ###
