"""Changes int_pk definition for autoincrement

Revision ID: 6c2309a47c60
Revises: 4d209dcd2f23
Create Date: 2024-06-27 19:42:59.416823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import schema


# revision identifiers, used by Alembic.
revision: str = '6c2309a47c60'
down_revision: Union[str, None] = '4d209dcd2f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(schema.CreateSequence(schema.Sequence("order_id_seq")))
    op.alter_column('orders','order_id',server_default=sa.text("nextval('order_id_seq'::regclass)"))
    op.execute(schema.CreateSequence(schema.Sequence("product_id_seq")))
    op.alter_column('products','product_id',server_default=sa.text("nextval('product_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop server defaults for order_id and product_id
    op.alter_column('orders', 'order_id', server_default=None)
    op.alter_column('products', 'product_id', server_default=None)
    
    # # Drop sequences
    op.execute(schema.DropSequence(schema.Sequence("order_id_seq")))
    op.execute(schema.DropSequence(schema.Sequence("product_id_seq")))
    # ### end Alembic commands ###
